Vagrant.configure("2") do |config|
  # config.vm.box = "bento/ubuntu-20.04"
  config.vm.box = "generic/ubuntu2204"
  config.vm.define "ifarahiS" do |controlS|
      controlS.vm.hostname = "ifarahiS"
      controlS.vm.network "private_network", ip: "192.168.56.110"
      controlS.vm.provider "virtualbox" do |v|
          v.memory = 1024
          v.cpus = 3
          v.name = "ifarahiS" # name appears in the VirtualBox GUI
          v.customize ["modifyvm", :id, "--name", "ifarahiS"]
      end
      controlS.vm.provision "shell", path: "scripts/setup.sh"
  end
end
